---
- name: Install editors and dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - emacs
    - fonts-symbola # required for custom floppy disc icon
    - neovim
    - silversearcher-ag
    - sqlite3 # sqlite3 is needed by emacs' helm-dash
    - vim
    - vim-fugitive
  become: yes
  tags: packages

- name: Clone spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ first_user.home }}/.emacs.d"
    update: no
  become: yes
  become_user: "{{ first_user.name }}"
  tags:
    - configuration
    - spacemacs

- name: Download .spacemacs
  get_url:
    url: "{{ dot_spacemacs_url }}"
    dest: "{{ first_user.home }}/.spacemacs"
    owner: "{{ first_user.name }}"
    group: "{{ first_user.name }}"
    force: no
  tags:
    - configuration
    - spacemacs

- name: Download .vimrc
  get_url:
    url: "{{ dot_vimrc_url }}"
    dest: "{{ first_user.home }}/.vimrc"
    owner: "{{ first_user.name }}"
    group: "{{ first_user.name }}"
    force: no
  tags:
    - configuration
    - vimrc

- name: Set vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  become: yes
  tags: configuration
