# sudo ansible-playbook break-stuff.yml --list-tags
# sudo ansible-playbook break-stuff.yml --diff --tags XXXXX --check
---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  roles:
    - { role: docker-install, tags: ['docker-install', 'docker'] }
    - { role: editors, tags: editors }
    - { role: git, tags: git }
    - { role: random-stuff, tags: random-stuff }
  tasks:
    - debug:
        msg: All done, have a nice day
      tags: always
