---
- hosts: local
  become: yes
  gather_facts: no
  roles:
    - { role: docker-install, tags: ['docker-install', 'docker'] }
    - { role: editors, tags: editors }
    - { role: git, tags: git }
  tasks:
    - debug:
        msg: All done, have a nice day
      tags: always
