# sudo ansible-playbook break-stuff.yaml --list-tags
# sudo ansible-playbook break-stuff.yaml --diff --tags XXXXX --check
---
- hosts: localhost
  connection: local
  roles:
    - { role: editors, tags: editors }
    - { role: git, tags: git }
    - { role: random-stuff, tags: random-stuff }
  tasks:
    - debug:
        msg: All done, have a nice day
      tags: always
