---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Add ansible ppa
      apt_repository:
        repo: 'ppa:ansible/ansible'

    - name: Install ansible
      apt:
        name: ansible
