# sudo ansible-playbook single.yaml -e task=XXXXX
---
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: first_user
  tasks:
    - include_tasks: "tasks/{{ task }}.yaml"
      tags: always
