---
- setup:
  when: ansible_user_dir is not defined
  tags: always

- name: Create zsh custom directories
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .zsh_custom/
    - .zsh_custom/plugins/

- name: Include local user dirs
  include_tasks:
    file: local-user-dirs.yaml
    apply:
      tags: minio
  tags: always

- name: Clone k
  git:
    repo: https://github.com/supercrabtree/k
    dest: "{{ ansible_user_dir }}/.zsh_custom/plugins/k"
    update: no

- name: Change k function to lk
  replace:
    path: "{{ ansible_user_dir }}/.zsh_custom/plugins/k/k.sh"
    regexp: '^k \(\) \{'
    replace: 'lk () {'

- name: Load k plugin in zsh
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: plugins+=(k)
    insertbefore: source \$ZSH/oh-my-zsh.sh

# https://github.com/sharkdp/fd
- name: Install fd-find
  apt:
    name: fd-find
  become: yes

- name: Add fd alias
  lineinfile:
    path: "{{ ansible_user_dir }}/.zsh_custom/alias.zsh"
    regexp: "alias fd=.*"
    line: alias fd=fdfind
    create: yes

- name: Install jq
  apt:
    name: jq
  become: yes

# Install bat https://github.com/sharkdp/bat
- name: Get bat deb url from github releases
  shell: >
      curl -s https://api.github.com/repos/sharkdp/bat/releases/latest
      | jq '.assets|.[].browser_download_url' -r
      | grep -v musl
      | grep amd64.deb
  args:
    warn: false
    creates: /usr/bin/bat
  register: bat_deb_url

- apt:
    deb: "{{ bat_deb_url.stdout }}"
  become: yes
  when: bat_deb_url is changed

- name: Add fzf-bat alias
  lineinfile:
    path: "{{ ansible_user_dir }}/.zsh_custom/alias.zsh"
    regexp: "alias fzf-bat=.*"
    line: alias fzf-bat="fzf --preview='bat --color always {}'"
    create: yes

# Install pet https://github.com/knqyf263/pet/
- name: Get pet deb url from github releases
  shell: >
      curl -s https://api.github.com/repos/knqyf263/pet/releases/latest
      | jq '.assets|map(select(.content_type=="application/x-debian-package"))[].browser_download_url' -r
      | grep amd64
  args:
    warn: false
    creates: /usr/local/bin/pet
  register: pet_deb_url
  tags: pet
- apt:
    deb: "{{ pet_deb_url.stdout }}"
  become: yes
  when: pet_deb_url is changed
  tags: pet

# Install yamldiff https://github.com/sahilm/yamldiff/
- name: Get yamldiff url from github releases
  shell: >
      curl -s https://api.github.com/repos/sahilm/yamldiff/releases/latest
      | jq '.assets|map(select(.content_type=="application/octet-stream"))[].browser_download_url' -r
      | grep linux-amd64
  args:
    warn: false
    creates: "{{ ansible_user_dir }}/.local/bin/yamldiff"
  register: yamldiff_url
  tags: yamldiff
- name: Download yamldiff
  get_url:
    url: "{{ yamldiff_url.stdout }}"
    dest: "{{ ansible_user_dir }}/.local/bin/yamldiff"
    mode: '0750'
  when: yamldiff_url is changed
  tags: yamldiff

- name: Download minio client (mc)
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: "{{ ansible_user_dir }}/.local/bin/minio-client"
    # checksum: 'sha256:231f9a902edbc7f35c4bb46583fbbeaeb960300f7585a74d82982caf5ddf68df'
    mode: 0755
  tags: minio
