---
- setup:
  when: ansible_user_dir is not defined

- name: Create zsh custom directories
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .zsh_custom/
    - .zsh_custom/plugins/

- name: Clone k
  git:
    repo: https://github.com/supercrabtree/k
    dest: "{{ ansible_user_dir }}/.zsh_custom/plugins/k"
    update: no

- name: Change k function to lk
  replace:
    path: "{{ ansible_user_dir }}/.zsh_custom/plugins/k/k.sh"
    regexp: '^k \(\) \{'
    replace: 'lk () {'

- name: Load k plugin in zsh
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: plugins+=(k)
    insertbefore: source \$ZSH/oh-my-zsh.sh

# https://github.com/sharkdp/fd
- name: Install fd-find
  apt:
    name: fd-find
  become: yes

- name: Add fd alias
  lineinfile:
    path: "{{ ansible_user_dir }}/.zsh_custom/alias.zsh"
    regexp: "alias fd=.*"
    line: alias fd=fdfind
    create: yes
