---
- name: Install python3-pip
  apt:
    name: python3-pip
  become: yes

- name: Install onkyo-eiscp
  pip:
    name: onkyo-eiscp
    executable: pip3
  become: yes

# https://github.com/miracle2k/onkyo-eiscp
# https://github.com/miracle2k/onkyo-eiscp/blob/master/eiscp-commands.yaml
# onkyo --discover
# onkyo system-power=off
# onkyo system-power=on
# onkyo volume=40
# onkyo input-selector=pc
# onkyo input-selector=strm-box
