# https://www.orgroam.com/manual/
# https://github.com/org-roam/org-roam/pull/133/files
# TODO: add org-roam to dotspacemacs-configuration-layers
---
- setup:
  when: ansible_user_dir is not defined
  tags: always

- name: Set local user facts
  include_tasks:
    file: local-user-facts.yaml
    apply:
      tags: always
  tags: always

- name: Org roam directory check
  fail:
    msg: |
      ansible localhost -i localhost, -c local -m ini_file -a 'path=~/.ansible-facts.d/defaults.fact section=user option=org_roam_directory value="~/Notes"'
  when: |
    ansible_local.defaults is not defined
    or ansible_local.defaults.user is not defined
    or ansible_local.defaults.user["org_roam_directory"] is not defined
  tags: always

- set_fact:
    org_roam_directory: "{{ ansible_local.defaults.user['org_roam_directory'] }}"
  tags: always

- name: Create org-roam directories
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ org_roam_directory }}"

- name: Install org-roam dependencies
  apt:
    name:
      - graphviz
      - sqlite3
  become: yes

- name: org-roam instructions
  debug:
    msg: |
      Add to dotspacemacs-configuration-layers:
      (org :variables
          org-enable-roam-support t
          org-roam-directory "{{ org_roam_directory }}"
          )

- name: Include org capture playbook
  include_tasks:
    file: tasks/org-capture.yaml
    apply:
      tags: org-capture
  tags: always
