- name: Install console tools
  apt:
    name:
      - ansible
      - build-essential
      - curl
      - fd-find
      - git
      - htop
      - nmap
      - ripgrep
      - silversearcher-ag
      - tmux
      - tree
      - wget

- name: Install desktop apps
  apt:
    name:
      - firefox
      - heif-gdk-pixbuf # avif support
      - meld
      - unison-gtk
      - vlc

- name: Install snap packages
  command: "snap install {{ item.name }} {{ item.options | default('') }}"
  args:
    chdir: /root
    creates: "/snap/{{ item.name }}"
  with_items:
    - { name: 'chromium' }
    - { name: 'languagetool' }
    - { name: 'spotify' }
  become: yes
  tags: snap

- name: Get snap connections
  command: "snap connections"
  register: snap_connections_output
  changed_when: no
  check_mode: no
  ignore_errors: yes
  tags: snap

- name: Remove snap connections
  command: "snap disconnect {{ item.interface }}"
  args:
    chdir: /root
  when: snap_connections_output.stdout.find(item.interface) != -1
  with_items:
    - { interface: 'languagetool:home' }
  become: yes
  tags: snap
