---
- setup:
  when: ansible_user_dir is not defined

- name: Add {{ ansible_user_id }} to dialout group
  user:
    name: "{{ ansible_user_id }}"
    groups: dialout
    append: yes
  become: yes

- name: Install Visual Studio Code platformio-ide extensions
  command: "/snap/bin/code --install-extension {{ item }} --force"
  args:
    creates: "{{ ansible_user_dir }}/.vscode/extensions/{{ item }}*"
  with_items:
    - ms-vscode.cpptools
    - platformio.platformio-ide
  tags: vscode

