# sudo true && ansible-playbook single.yaml --diff -e task=pyenv
---
- name: Setup ansible_user_dir
  setup:
  when: ansible_user_dir is not defined
  tags: always

- name: Set common facts
  set_fact:
    zsh_custom_dir: "{{ ansible_user_dir }}/.zsh_custom"
    venv_dir: "{{ ansible_user_dir }}/.virtualenvs"

# https://github.com/pyenv/pyenv#installation
- name: Install pyenv packages
  apt:
    name:
      - build-essential
      - curl
      - git
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev
  become: yes

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    version: master
    dest: "{{ ansible_user_dir }}/.pyenv"

- name: zsh completion
  file:
    state: link
    src: ~/.pyenv/completions/pyenv.zsh
    dest: "{{ zsh_custom_dir }}/pyenv-completion.zsh"

- name: pyenv zsh integration
  copy:
    content: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
          eval "$(pyenv init -)"
      fi

    dest: "{{ zsh_custom_dir }}/pyenv.zsh"
    mode: 0644

- name: Check if python 3.7 exists
  stat:
    # path: "{{ ansible_user_dir }}/.pyenv/shims/python3.7"
    path: "{{ ansible_user_dir }}/.pyenv/versions/3.7.7/bin/python3.7"
  register: pyenv_python_3_7
  tags:
    - never
    - install-python

- name: Install python 3.7.7
  command:
    argv:
      - /usr/bin/zsh
      - -c
      - export PYENV_ROOT="$HOME/.pyenv" && export PATH="$PYENV_ROOT/bin:$PATH" && eval "$(pyenv init -)" && pyenv install 3.7.7
  when: not pyenv_python_3_7.stat.exists
  tags:
    - never
    - install-python
