# sudo true && ansible-playbook single.yaml --diff -e task=rbenv
---
- name: Setup ansible_user_dir
  setup:
  when: ansible_user_dir is not defined

- name: Set common facts
  set_fact:
    zsh_custom_directory: "{{ ansible_user_dir }}/.zsh_custom"

- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ ansible_user_dir }}/.rbenv"

- name: Clone rbenv plugins
  git:
    repo: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.rbenv/plugins/{{ item | basename }}"
  with_items:
    - https://github.com/rbenv/rbenv-vars
    - https://github.com/rbenv/ruby-build

- name: Zsh completion
  file:
    state: link
    src: ~/.rbenv/completions/rbenv.zsh
    dest: "{{ zsh_custom_directory }}/rbenv-completion.zsh"

- copy:
    content: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
    dest: "{{ zsh_custom_directory }}/rbenv.zsh"
    mode: 0644
