# sudo true && ansible-pull -U https://github.com/vsakarov/ansible/ single.yaml -e task=ssh-key -e ssh_key_name=id_rsa
# sudo true && ansible-playbook single.yaml --diff -e task=ssh-key -e ssh_key_name=id_rsa
---
- name: Install ssh package
  apt:
    name:
      - openssh-client
  become: yes

- name: asdf
  set_fact:
    ssh_key_name: id_rsa

- name: Setup ansible_user_dir
  setup:
  when: ansible_user_dir is not defined

- name: Check whether ssh key exists
  stat:
    path: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_name }}"
  register: key_file

- name: "Password prompt"
  pause:
    prompt: 'Enter password for your ssh key'
    echo: no
  register: key_pass
  when: not key_file.stat.exists

- name: Password length check
  fail:
    msg: Password too short
  when: not key_file.stat.exists and key_pass.user_input | length < 4

- name: Create 4096 bit ssh key for user {{ ansible_user_id }} named {{ ssh_key_name }}
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "ansible-{{ ansible_hostname }}"
    ssh_key_file: ".ssh/{{ ssh_key_name }}"
    ssh_key_passphrase: "{{ key_pass.user_input }}"
    ssh_key_type: rsa
  when: not key_file.stat.exists

- name: Slurp ssh public key
  slurp:
    src: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_name }}.pub"
  register: public_key

# https://docs.ansible.com/ansible/latest/modules/known_hosts_module.html
- name: Add github to known hosts
  known_hosts:
    name: github.com
    path: "{{ ansible_user_dir }}/.ssh/known_hosts"
    hash_host: yes
    # $ ssh-keyscan -t rsa github.com
    key: >-
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

- name: Pring public key
  debug:
    msg: |
      Go to https://github.com/settings/ssh/new and upload your public key

      {{ public_key['content'] | b64decode }}
  changed_when: yes
