---
- name: Install snap packages
  command: "snap install {{ item.name }} {{ item.options | default('') }}"
  args:
    chdir: /root
    creates: "/snap/{{ item.name }}"
  with_items:
    - { name: 'code', options: '--classic' }
  become: yes
  tags: snap

- setup:
  when: ansible_user_dir is not defined

- name: Install Visual Studio Code extensions
  command: "/snap/bin/code --install-extension {{ item }} --force"
  args:
    creates: "{{ ansible_user_dir }}/.vscode/extensions/{{ item }}*"
  with_items:
    - ms-python.python
    - vscodevim.vim
    - vscoss.vscode-ansible
  tags: extensions

- name: Configure VSpaceCode
  command: "curl -s {{ item.url }} -o {{ item.dest }}"
  args:
    chdir: "{{ ansible_user_dir }}/.config/Code/User/"
    creates: "{{ ansible_user_dir }}/.config/Code/User/{{ item.dest }}"
    warn: false # get_url doesn't support creates
  with_items:
    - { url: 'https://raw.githubusercontent.com/VSpaceCode/VSpaceCode/master/keybindings.json', dest: 'keybindings.json' }
    - { url: 'https://raw.githubusercontent.com/VSpaceCode/VSpaceCode/master/settings.json', dest: 'settings.json' }
  tags: configuration
