# ansible-playbook single.yaml --diff -e task=zsh-jumps -e work_dir=~/w/
---
- name: Find directories in {{ work_dir }}
  find:
    paths: "{{ work_dir }}"
    file_type: directory
  register: work_dir_list
  when: work_dir is defined

- setup:
  when: ansible_user_dir is not defined

- name: Create marks directory
  file:
    path: "{{ ansible_user_dir }}/.marks"
    state: directory
    mode: 0755
  when: work_dir is defined

- name: Create zsh jumps
  file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.marks/{{ item | basename }}"
    state: link
  with_items: "{{ work_dir_list.files | map(attribute='path') | list }}"
  when: work_dir is defined
