---
- name: Install git
  package:
    name: git
  become: yes
  tags: packages

- name: Setup git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: alias.amend, value: commit --amend }
    - { name: alias.br, value: branch }
    - { name: alias.ci, value: commit }
    - { name: alias.co, value: checkout }
    - { name: alias.cp, value: cherry-pick }
    - { name: alias.di, value: diff }
    - { name: alias.dw, value: diff --word-diff }
    - { name: alias.remove-merged, value: "!git branch --merged | grep -v 'master\\|^\\*' | xargs --no-run-if-empty git br -d" }
    - { name: alias.st, value: status }
    - { name: color.ui, value: 'true' }
    - { name: push.default, value: simple }
  tags: configuration
