---
- name: Install git
  package:
    name: git
  become: yes
  tags: packages

- name: Setup git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: alias.amend, value: commit --amend }
    - { name: alias.br, value: branch }
    - { name: alias.ci, value: commit }
    - { name: alias.co, value: checkout }
    - { name: alias.cp, value: cherry-pick }
    - { name: alias.di, value: diff }
    - { name: alias.dw, value: diff --word-diff }
    - { name: alias.remove-merged, value: "!git branch --merged | grep -v 'master\\|^\\*' | xargs --no-run-if-empty git br -d" }
    - { name: alias.prune-branches, value: fetch origin --prune }
    - { name: alias.st, value: status }
    - { name: color.ui, value: 'true' }
    - { name: core.excludesfile, value: "{{ ansible_user_dir }}/.gitignore" }
    - { name: push.default, value: simple }
  tags: configuration

- name: Gather local user facts
  setup:
    fact_path: "{{ ansible_user_dir }}/.ansible-facts.d"
    filter: ansible_local
    gather_subset: min

- name: Configure git user settings
  git_config:
    name: "{{ item }}"
    scope: global
    value: "{{ ansible_local.defaults.git[item] }}"
  loop:
    - user.name
    - user.email
  when: |
    ansible_local.defaults is defined
    and ansible_local.defaults.git is defined
    and ansible_local.defaults.git[item] is defined

- name: Show git settings info
  debug:
    msg: Show git settings info
  notify: No git settings
  changed_when: |
    ansible_local.defaults is not defined
    or ansible_local.defaults.git is not defined
    or ansible_local.defaults.git['user.name'] is not defined
    or ansible_local.defaults.git['user.email'] is not defined
