- name: Install all noto fonts
  apt:
    name: fonts-noto
  become: yes
  tags:
    - noto
    - never

- name: Create fonts directory
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .local
    - .local/share
    - .local/share/fonts
  tags: configuration

- name: Download source code pro
  git:
    repo: https://github.com/adobe-fonts/source-code-pro
    version: release
    depth: 1
    dest: "{{ ansible_user_dir }}/.local/share/fonts/source-code-pro"
    update: no
  notify: Recreate fontconfig cache
  tags: configuration

- name: Download Cascadia
  get_url:
    url: https://github.com/microsoft/cascadia-code/releases/download/v1911.21/Cascadia.ttf
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Cascadia.ttf"
  notify: Recreate fontconfig cache
  tags: configuration
