- name: Install console tools
  apt:
    name:
      - ansible
      - aptitude
      - arp-scan
      - build-essential
      - curl
      - exuberant-ctags
      - fd-find
      - git
      - htop
      - mosh
      - nmap
      - ripgrep
      - silversearcher-ag
      - tmux
      - tree
      - vim
      - wget

- name: Install desktop apps
  apt:
    name:
      - chromium-browser
      - firefox
      - meld
      - unison-gtk
      - vlc

- name: Install snap packages
  command: "snap install {{ item.name }} {{ item.options | default('') }}"
  args:
    chdir: /root
    creates: "/snap/{{ item.name }}"
  with_items:
    - { name: 'languagetool' }
    - { name: 'skype', options: '--classic' }
    - { name: 'spotify' }
  become: yes
  tags: snap

- name: Get snap connections
  command: "snap connections"
  register: snap_connections_output
  changed_when: no
  check_mode: no
  ignore_errors: yes
  tags: snap

- name: Remove snap connections
  command: "snap disconnect {{ item.interface }}"
  args:
    chdir: /root
  when: snap_connections_output.stdout.find(item.interface) != -1
  with_items:
    - { interface: 'languagetool:home' }
  become: yes
  tags: snap
