- name: Install console tools
  apt:
    name:
      - ansible
      - aptitude
      - arp-scan
      - build-essential
      - curl
      - exuberant-ctags
      - fd-find
      - git
      - htop
      - mosh
      - nmap
      - ripgrep
      - silversearcher-ag
      - tmux
      - tree
      - vim
      - wget

- name: Install desktop apps
  apt:
    name:
      - chromium-browser
      - firefox
      - meld
      - unison-gtk
      - vlc

- name: Install snap packages
  command: "snap install {{ item.name }} {{ item.options | default('') }}"
  args:
    chdir: /root
    creates: "/snap/{{ item.name }}"
  with_items:
    - { name: 'spotify' }
    - { name: 'skype', options: '--classic' }
  become: yes
  tags: snap
