---
- name: Install tmux and plugin dependencies
  apt:
    name:
      - tmux
      - xsel
  become: yes
  tags: packages

- set_fact:
    tmux_plugin_path: "{{ ansible_user_dir }}/.config/tmux-plugins"
    tmux_plugin_path_relative: "~/.config/tmux-plugins"

- name: Create tmux plugin directory
  file:
    state: directory
    path: "{{ tmux_plugin_path }}"
  tags: configuration

- name: Clone tmux plugins
  git:
    repo: "{{ item }}"
    dest: "{{ tmux_plugin_path }}/{{ item | basename }}"
    update: no
  tags: configuration
  loop:
    - https://github.com/tmux-plugins/tmux-copycat
    - https://github.com/tmux-plugins/tmux-logging
    - https://github.com/tmux-plugins/tmux-open
    - https://github.com/tmux-plugins/tmux-yank

# # Following should be set at the bottom of .tmux.conf
# set-environment -g TMUX_PLUGIN_MANAGER_PATH '{{ tmux_plugin_path_relative }}/'
# run '{{ tmux_plugin_path_relative }}/tpm/tpm'

- name: Download .tmux.conf
  get_url:
    url: "{{ dot_tmux_conf_url }}"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    force: no
  tags:
    - configuration
