- name: Install zsh
  apt:
    name:
      - command-not-found
      - zsh
  become: yes
  tags: packages

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh/
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    update: no
  tags:
    - configuration
    - oh-my-zsh

- name: Download .zshrc
  get_url:
    url: "{{ dot_zshrc_url }}"
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: no
  tags:
    - configuration
    - oh-my-zsh

- name: Create zsh directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ansible_user_dir }}/.marks"
    - "{{ ansible_user_dir }}/.zsh_custom"

- name: Add some aliases
  lineinfile:
    path: "{{ zsh_custom_directory }}/alias.zsh"
    regexp: "^[#\\s]*alias\\s+{{ item.alias | regex_escape() }}="
    line: "alias {{ item.alias }}=\"{{ item.value }}\""
    create: yes
  with_items:
    - { alias: 'e', value: 'editor' }
    - { alias: 'j', value: 'jump' }
    - { alias: 'o', value: 'xdg-open' }

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: "{{ ansible_user_dir }}/.fzf"
    update: no
  tags:
    - configuration
    - fzf

# TODO: Don't depend on versioned url
- name: Download fzf executable
  unarchive:
    src: https://github.com/junegunn/fzf-bin/releases/download/0.17.5/fzf-0.17.5-linux_amd64.tgz
    dest: "{{ ansible_user_dir }}/.fzf/bin/"
    remote_src: yes
    creates: "{{ ansible_user_dir }}/.fzf/bin/fzf"
  tags:
    - configuration
    - fzf

- name: Configure fzf loading
  copy:
    content: |
      export FZF_HOME=~/.fzf/
      # Setup fzf
      # ---------
      if [[ ! "$PATH" == *$FZF_HOME/bin* ]]; then
        export PATH="$PATH:$FZF_HOME/bin"
      fi

      # Auto-completion
      # ---------------
      [[ $- == *i* ]] && source "$FZF_HOME/shell/completion.zsh" 2> /dev/null

      # Key bindings
      # ------------
      source "$FZF_HOME/shell/key-bindings.zsh"

    dest: "{{ zsh_custom_directory }}/fzf.zsh"
    mode: 0644
  tags:
    - configuration
    - fzf

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.zsh_custom/plugins/zsh-autosuggestions"
    update: no
  tags:
    - configuration
    - oh-my-zsh

- name: Set {{ ansible_user_id }} shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
