# -*- coding: utf-8 -*-
- name: Install zsh
  apt:
    name:
      - command-not-found
      - fzf
      - zsh
  become: yes
  tags:
    - packages
    - zsh

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    version: master
    update: no
  tags:
    - configuration
    - oh-my-zsh

- name: Copy .zshrc template from oh my zsh
  copy:
    src: "{{ ansible_user_dir }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_user_dir }}/.zshrc"
    remote_src: yes
    force: no
  tags:
    - configuration
    - oh-my-zsh
    - zshrc

- name: Create custom zsh theme
  copy:
    content: |
      # This theme is copy of aussiegeek with zero width space at the end of the prompt used for tmux jumping
      NBSP=" "
      PROMPT='$fg_bold[blue][ $fg[red]%t $fg_bold[blue]] $fg_bold[blue] [ $fg[red]%n@%m:%~$(git_prompt_info)$fg_bold[blue] ]$reset_color$NBSP
      $ '
      # git theming
      ZSH_THEME_GIT_PROMPT_PREFIX="$fg_bold[green]("
      ZSH_THEME_GIT_PROMPT_SUFFIX=")"
      ZSH_THEME_GIT_PROMPT_CLEAN="✔"
      ZSH_THEME_GIT_PROMPT_DIRTY="✗"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/themes/vasil.zsh-theme"
  tags:
    - configuration
    - oh-my-zsh
    - zshrc

- name: Set custom variables in zshrc
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: "^[# ]*{{ item.name }}="
    line: '{{ item.name }}="{{ item.value }}"'
    insertbefore: source \$ZSH/oh-my-zsh.sh
  loop:
    - { name: "COMPLETION_WAITING_DOTS", value: "true" }
    - { name: "DISABLE_AUTO_UPDATE", value: "true" }
    - { name: "DISABLE_UNTRACKED_FILES_DIRTY", value: "true" }
    - { name: "ZSH_CUSTOM", value: "$HOME/.zsh_custom/" }
    - { name: "ZSH_THEME", value: "vasil" }
    - { name: "ZSH_TMUX_AUTOSTART", value: "true" }
    - { name: "ZSH_TMUX_AUTOQUIT", value: "false" }
  tags:
    - configuration
    - oh-my-zsh
    - zshrc

- name: Load oh-my-zsh plugins
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: plugins+=({{ item }})
    insertbefore: source \$ZSH/oh-my-zsh.sh
  loop:
    - command-not-found
    - jump
    - tmux
    - zsh-autosuggestions

- name: Create zsh directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ansible_user_dir }}/.marks"
    - "{{ ansible_user_dir }}/.zsh_custom"

- name: Add some aliases
  lineinfile:
    path: "{{ zsh_custom_directory }}/alias.zsh"
    regexp: "^[#\\s]*alias\\s+{{ item.alias | regex_escape() }}="
    line: "alias {{ item.alias }}=\"{{ item.value }}\""
    create: yes
  with_items:
    - { alias: 'e', value: 'editor' }
    - { alias: 'j', value: 'jump' }
    - { alias: 'o', value: 'xdg-open' }

- name: Remove manually installed fzf
  file:
    state: absent
    path: "{{ ansible_user_dir }}/.fzf"
  tags:
    - configuration
    - fzf

# https://www.freecodecamp.org/news/fzf-a-command-line-fuzzy-finder-missing-demo-a7de312403ff/
- name: Configure fzf loading
  copy:
    content: |
      source /usr/share/doc/fzf/examples/key-bindings.zsh

      # Auto completion: ls **<tab>
      [[ $- == *i* ]] && source /usr/share/zsh/vendor-completions/_fzf 2> /dev/null
    dest: "{{ zsh_custom_directory }}/fzf.zsh"
    mode: 0644
  tags:
    - configuration
    - fzf

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.zsh_custom/plugins/zsh-autosuggestions"
    version: master
    update: no
  tags:
    - configuration
    - oh-my-zsh

- name: Set {{ ansible_user_id }} shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
